# Generated by Django 5.1.2 on 2025-01-11 16:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Druzyna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('miasto', models.CharField(max_length=100)),
                ('stadion', models.CharField(max_length=100)),
                ('data_zalozenia', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Stanowisko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=80)),
                ('opis', models.TextField()),
            ],
            options={
                'verbose_name': 'Stanowisko',
                'verbose_name_plural': 'Stanowiska',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'Klub',
                'verbose_name_plural': 'Kluby',
            },
        ),
        migrations.CreateModel(
            name='Trener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('data_urodzenia', models.DateField()),
                ('narodowosc', models.CharField(max_length=50)),
                ('lata_doswiadczenia', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mecz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('stadion', models.CharField(max_length=100)),
                ('wynik_gospodarz', models.PositiveIntegerField(default=0)),
                ('wynik_gosc', models.PositiveIntegerField(default=0)),
                ('druzyna_gosc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mecze_gosc', to='My_Squad_App.druzyna')),
                ('druzyna_gospodarz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mecze_gospodarz', to='My_Squad_App.druzyna')),
            ],
        ),
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=40)),
                ('nazwisko', models.CharField(max_length=60)),
                ('plec', models.IntegerField(choices=[(1, 'Kobieta'), (2, 'Mężczyzna'), (3, 'Inna')], default=3)),
                ('country', models.CharField(default='', max_length=3)),
                ('data_dodania', models.DateField(default=datetime.date.today)),
                ('stanowisko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My_Squad_App.stanowisko')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='My_Squad_App.team')),
            ],
            options={
                'verbose_name': 'Osoba',
                'verbose_name_plural': 'Osoby',
                'ordering': ['nazwisko'],
            },
        ),
        migrations.AddField(
            model_name='druzyna',
            name='trener',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='My_Squad_App.trener'),
        ),
        migrations.CreateModel(
            name='Trening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('czas_trwania_minuty', models.PositiveIntegerField()),
                ('obszar_skupienia', models.CharField(max_length=100)),
                ('druzyna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treningi', to='My_Squad_App.druzyna')),
            ],
        ),
        migrations.CreateModel(
            name='Zawodnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('data_urodzenia', models.DateField()),
                ('pozycja', models.CharField(choices=[('BR', 'Bramkarz'), ('OB', 'Obrońca'), ('PP', 'Pomocnik'), ('NA', 'Napastnik')], max_length=2)),
                ('numer_koszulki', models.PositiveIntegerField()),
                ('narodowosc', models.CharField(max_length=50)),
                ('druzyna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zawodnicy', to='My_Squad_App.druzyna')),
            ],
        ),
        migrations.CreateModel(
            name='StatystykiZawodnika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bramki', models.PositiveIntegerField(default=0)),
                ('asysty', models.PositiveIntegerField(default=0)),
                ('zolte_kartki', models.PositiveIntegerField(default=0)),
                ('czerwone_kartki', models.PositiveIntegerField(default=0)),
                ('minuty_na_boisku', models.PositiveIntegerField(default=0)),
                ('mecz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statystyki_zawodnikow', to='My_Squad_App.mecz')),
                ('zawodnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statystyki', to='My_Squad_App.zawodnik')),
            ],
        ),
    ]
