# Generated by Django 5.1.2 on 2025-01-17 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Squad_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='druzyna',
            options={'verbose_name': 'Drużyna', 'verbose_name_plural': 'Drużyny'},
        ),
        migrations.AlterModelOptions(
            name='mecz',
            options={'verbose_name': 'Mecz', 'verbose_name_plural': 'Mecze'},
        ),
        migrations.AlterModelOptions(
            name='statystykizawodnika',
            options={'verbose_name_plural': 'Statystyki'},
        ),
        migrations.AlterModelOptions(
            name='trener',
            options={'verbose_name': 'Trener', 'verbose_name_plural': 'Trenerzy'},
        ),
        migrations.AlterModelOptions(
            name='trening',
            options={'verbose_name': 'Trening', 'verbose_name_plural': 'Treningi'},
        ),
        migrations.AlterModelOptions(
            name='zawodnik',
            options={'verbose_name': 'Zawodnik', 'verbose_name_plural': 'Zawodnicy'},
        ),
        migrations.RemoveField(
            model_name='druzyna',
            name='data_zalozenia',
        ),
        migrations.AddField(
            model_name='druzyna',
            name='rok_zalozenia',
            field=models.IntegerField(default=1900, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2025)]),
            preserve_default=False,
        ),
    ]
