# Generated by Django 5.1.2 on 2025-01-17 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_Squad_App', '0002_alter_druzyna_options_alter_mecz_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zawodnik',
            options={'ordering': ['pozycja', 'nazwisko'], 'verbose_name': 'Zawodnik', 'verbose_name_plural': 'Zawodnicy'},
        ),
    ]
