# Generated by Django 5.1.2 on 2025-01-21 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Squad_App', '0003_alter_zawodnik_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osoba',
            name='stanowisko',
        ),
        migrations.RemoveField(
            model_name='osoba',
            name='team',
        ),
        migrations.AlterField(
            model_name='statystykizawodnika',
            name='czerwone_kartki',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='statystykizawodnika',
            name='minuty_na_boisku',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='statystykizawodnika',
            name='zolte_kartki',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.DeleteModel(
            name='Stanowisko',
        ),
        migrations.DeleteModel(
            name='Osoba',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
